# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    parallelism: 1 # run one (three) instances of this job in parallel
    working_directory: ~/circleci-coderschool-website # directory where steps will run
    docker: # run the steps with Docker
      # specify the version you desire here
      - image: circleci/ruby:2.4.1-node-browsers  # ...with this image as the primary container; this is where all `steps` will run
        environment: # environment variables for primary container
          # BUNDLE_JOBS: 3
          # BUNDLE_RETRY: 3
          # BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: circleci-postgres
          RAILS_ENV: test
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.4.18
        environment: # environment variables for database
          POSTGRES_USER: circleci-postgres
          POSTGRES_DB: moon_project_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      # Restore bundle cache
      - run: whoami
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Update bundler
          command: |
            gem install bundler
            bundle -v

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
          
      - run:
          name: Download postgresql-client (update and install missing packages before hand)
          command: |          
            sudo apt-get update
            sudo apt-get install --fix-missing
            sudo apt install postgresql-client-9.4
      
      # Which version of ruby, rails, and psql?
      - run:
          name: Ruby, Rails, PostgreSQL version
          command: |     
            ruby -v
            bin/rails -v
            psql --version

      # Store bundle cache
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      
      # Database setup
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: bin/rails db:create

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      # run tests!
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
          when: always 
      # Save test results for timing analysis
      - store_test_results:
          path: test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for example deploy configs